package style

import (
	"crypto/sha256"
	"encoding/hex"
	"regexp"
	"strings"
	"unicode"
)

// Values are masked by default wherever prizm prints a diff.
//
// The tool exists to hold credentials, and its most-used commands — `up
// --dry-run`, `sync`, `audit` — print old and new values side by side. Run any
// of them while screen-sharing, in a logged terminal, or in CI output, and the
// secret is in someone else's scrollback. Masking is the default because the
// unsafe case is the invisible one: nobody remembers to pass --safe.
var showValues bool

// ShowValues reveals values for this process. Wired to --show-values.
func ShowValues() { showValues = true }

// userinfo matches the credential embedded in a connection string, with or
// without a scheme: both postgres://user:pass@host and user:pass@host.
//
// The password may contain anything except @ and whitespace — an earlier
// version excluded "/" too, which meant a password generated by `openssl rand
// -base64` failed to match roughly half the time and the whole URL printed.
var userinfo = regexp.MustCompile(
	`(?s)^\s*((?:[a-zA-Z][\w+.-]*://)?)([^:/@\s]+):([^@\s]+)@`)

// sensitiveKey matches names that conventionally hold a credential.
//
// "key" is here without a qualifier: SIGNING_KEY and ENCRYPTION_KEY are as
// much a credential as API_KEY, and a rule that only knows the qualified forms
// misses whatever someone names next.
var sensitiveKey = regexp.MustCompile(
	`(?i)(secret|password|passwd|pwd|pass\b|token|key|credential|auth|salt|` +
		`signature|hmac|bearer|cookie|session|jwt|dsn|conn|private|cert\b|pat\b|sas\b)`)

// A PEM block is unambiguous whatever it is called.
var pemBlock = regexp.MustCompile(`-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----`)

// Names that read as sensitive but almost never are. Without these, AUTHOR
// masks on "auth" and CERT_PATH on "cert", which makes an ordinary diff
// unreadable — and a diff nobody can read is a diff nobody checks.
var benignKey = regexp.MustCompile(`(?i)^(author|authors|authority|.*_path|path|.*_file|.*_url|.*_uri|.*_host|.*_origin|.*_region|.*_env)$`)

// Secret renders a value for display, masking it unless it is plainly benign.
//
// Both the key and the value are consulted. A name-only rule misses PAC_SECRET
// renamed to PAC_S; a value-only rule masks every URL. Taking the union errs
// toward masking, which is the direction to err in.
func Secret(key, value string) string {
	if showValues || strings.TrimSpace(value) == "" {
		return value
	}

	named := sensitiveKey.MatchString(key) && !benignKey.MatchString(key)

	// A connection string is redacted rather than replaced: the host and
	// database are the useful half of a diff, and only the password needs
	// hiding. That only holds when the key itself is not a credential —
	// otherwise the tail can carry one too, in a query parameter.
	if m := userinfo.FindStringSubmatch(value); m != nil && !named {
		rest := value[len(m[0]):]
		return strings.TrimLeft(value[:len(m[1])], " \t\n") + m[2] + ":" + mask(m[3]) + "@" + rest
	}

	if named || looksSecret(value) {
		return mask(value)
	}
	return value
}

// looksSecret reports whether a value has the shape of a credential
// independently of what it is called.
func looksSecret(value string) bool {
	v := strings.TrimSpace(value)

	if pemBlock.MatchString(v) {
		return true
	}
	if userinfo.MatchString(v) {
		return true
	}

	// A URL, a path, or a sentence is not a credential. Checked before the
	// entropy rules so ordinary configuration stays readable.
	if strings.Contains(v, "://") || strings.HasPrefix(v, "/") || strings.Contains(v, " ") {
		return false
	}
	if strings.ContainsAny(v, ",") {
		return false
	}

	// Long unbroken tokens are credentials whatever their alphabet: a 20-digit
	// PIN and a 32-character passphrase are both secrets, and requiring mixed
	// character classes exempted exactly those.
	return len(v) >= 20 && !hasWordBreak(v)
}

// hasWordBreak reports whether a string reads as prose or an identifier rather
// than as a generated token.
func hasWordBreak(s string) bool {
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) &&
			r != '_' && r != '-' && r != '+' && r != '/' && r != '=' && r != '.' {
			return true
		}
	}
	return false
}

// mask replaces a value with a stable fingerprint.
//
// A fingerprint rather than a row of dots: a diff has to answer "which of
// these two is the production key", and it can only do that if the same value
// renders the same way every time. Four hex characters distinguish values
// without being enough to reconstruct one.
func mask(value string) string {
	sum := sha256.Sum256([]byte(strings.TrimSpace(value)))
	return "••••" + hex.EncodeToString(sum[:])[:4]
}
